//auth
export const IS_AUTHORIZED = "IS_AUTHORIZED";
export const IS_LOGOUT = "IS_LOGOUT";
export const SET_USER_ERROR = "SET_USER_ERROR";

//exercise
export const GET_ALL_EXERCISE = "GET_ALL_EXERCISE";
export const SET_EXERCISE_LOADING = "SET_EXERCISE_LOADING";
export const CREATE_NEW_EXERCISE = "CREATE_NEW_EXERCISE";
export const DELETE_EXERCISE = "DELETE_EXERCISE";
export const UPDATE_EXERCISE = "UPDATE_EXERCISE";
